n: 1000
k: 500
method1: elite
method2: ranking
method3: roulette
method4: universal
a: 0.7
b: 0.3
crossover_method: one point
mutation_method: gene
mutation_probability: 0.05
replacement_method: fill all
character_type: warrior
finish: generations
generations_limit: 1000
